# Generated by Django 4.0 on 2021-12-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTorneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
                ('estacionamiento', models.CharField(max_length=40)),
                ('vestuarios', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('sede', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
                ('inicio', models.DateField()),
                ('inscripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
