# Generated by Django 4.0 on 2022-01-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTorneo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
