# Generated by Django 4.0 on 2021-12-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTorneo', '0002_sede_torneo_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='inscripcion',
        ),
        migrations.AlterField(
            model_name='sede',
            name='estacionamiento',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='vestuarios',
            field=models.BooleanField(),
        ),
    ]
